---
- name: Testing andrewrothstein.kustomize
  hosts: all
  tasks:
    - name: Installing andrewrothstein.kustomize
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'kustomize version'
      ansible.builtin.command: /usr/local/bin/kustomize version
      changed_when: false
      register: kustomize_test_output
    - name: Output from 'kustomize version'
      ansible.builtin.debug:
        msg: '{{ kustomize_test_output.stdout }}'
